---
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - jruby
  - rbx
matrix:
  include:
    - { rvm: 1.9.3, env: rouge=master }
    - { rvm: 2.0.0, env: rouge=master }
    - { rvm: 2.1.0, env: rouge=master }
    - { rvm: ruby-head, env: rouge=master }
    - { rvm: jruby, env: rouge=master }
  allow_failures:
    - rvm: rbx
notifications:
  recipients:
    - zachary@zacharyscott.net
